// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDzZuQN6k7w8kZTG0EkHcamSI_3fT_auB0',
    appId: '1:987521462078:web:3af7545fef3bdc781e466f',
    messagingSenderId: '987521462078',
    projectId: 'aplikasi-peminjman',
    authDomain: 'aplikasi-peminjman.firebaseapp.com',
    storageBucket: 'aplikasi-peminjman.appspot.com',
    measurementId: 'G-CF6HRMDRSP',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAUbfStAAw8KnHLDoUXQ2UrBVHmrZbYZqE',
    appId: '1:987521462078:android:4e7a104aa3471dcc1e466f',
    messagingSenderId: '987521462078',
    projectId: 'aplikasi-peminjman',
    storageBucket: 'aplikasi-peminjman.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyApjxtkRT_7B1umiFJupeu2Z8ytpW4lFrY',
    appId: '1:987521462078:ios:40507e412ee6b4291e466f',
    messagingSenderId: '987521462078',
    projectId: 'aplikasi-peminjman',
    storageBucket: 'aplikasi-peminjman.appspot.com',
    iosBundleId: 'com.example.aplikasiPeminjaman',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyApjxtkRT_7B1umiFJupeu2Z8ytpW4lFrY',
    appId: '1:987521462078:ios:cd8febdfa614add91e466f',
    messagingSenderId: '987521462078',
    projectId: 'aplikasi-peminjman',
    storageBucket: 'aplikasi-peminjman.appspot.com',
    iosBundleId: 'com.example.aplikasiPeminjaman.RunnerTests',
  );
}
